- name: Install docker
  community.general.pacman:
    name: docker
    extra_args: "--noconfirm"
    state: present
  become: yes
  tags: docker

- name: Enable docker service
  ansible.builtin.systemd:
    state: started
    name: docker
    enabled: yes
  become: yes

- name: Add current user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  become: yes