- name: Install tmux
  community.general.pacman:
    name: tmux
    extra_args: "--noconfirm"
    state: present
  become: yes
  tags: tmux

- name: Configure tmux
  copy:
    src: tmux.conf
    dest: ~/.tmux.conf
  