- name: Enable AUR repository
  replace:
    path: /etc/pamac.conf
    regexp: "#EnableAUR"
    replace: "EnableAUR"
  become: yes

- name: Enable AUR repository updates
  replace:
    path: /etc/pamac.conf
    regexp: "#CheckAURUpdates"
    replace: "CheckAURUpdates"
  become: yes

- name: Update pacman cache and upgrade
  community.general.pacman:
    update_cache: yes
    upgrade: yes
    upgrade_extra_args: "--noconfirm"
  become: yes

- name: Install pacman base packages 
  community.general.pacman:
    name: "{{ item }}"
    extra_args: "--noconfirm"
    state: present
  with_items: "{{ pacman_packages }}"
  become: yes