- name: Install pacman base packages 
  community.general.pacman:
    name: "{{ item }}"
    extra_args: "--noconfirm"
    state: present
  with_items: "{{ pacman_packages }}"
  become: yes
  
- name: Configure tmux
  copy:
    src: tmux.conf
    dest: ~/.tmux.conf
  tags: tmux