- name: Enable AUR repository
  replace:
    path: /etc/pamac.conf
    regexp: "#EnableAUR"
    replace: "EnableAUR"
  become: yes
  tags: pacman

- name: Enable AUR repository updates
  replace:
    path: /etc/pamac.conf
    regexp: "#CheckAURUpdates"
    replace: "CheckAURUpdates"
  become: yes
  tags: pacman

- name: Update pacman cache and upgrade
  community.general.pacman:
    update_cache: yes
    upgrade: yes
    upgrade_extra_args: "--noconfirm"
  become: yes
  tags: pacman