- name: Enable Snap repository
  replace:
    path: /etc/pamac.conf
    regexp: "#EnableSnap"
    replace: "EnableSnap"
  become: yes

- name: Enable support of classic Snap
  ansible.builtin.file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link
  become: yes